Config = {}

Config.RandomItemAmount = 3
Config.RewardItems = {
    {label = 'Grilled Sandwich', item = 'tosti'},
    {label = 'Sandwich', item = 'sandwich'},
    {label = 'Snikkel bar', item = 'snikkel_candy'},
    {label = 'Twerks bar', item = 'twerks_candy'},
    {label = 'Water Bottle', item = 'water_bottle'},
    {label = 'Coca Cola', item = 'kurkakola'},
    {label = 'lighter', item = 'lighter'},
    {label = 'Fireworks', item = 'firework1'},
    {label = 'Fireworks', item = 'firework2'},
    {label = 'Bandage', item = 'bandage'},
    {label = 'Painkillers', item = 'painkillers'},
    {label = 'Rolling Paper', item = 'rolling_paper'},
}

Config.CoolDownTimer = 60

Config.MaleNoVest = {
    [0] = true, [1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [9] = true, [10] = true, [11] = true, [12] = true, [13] = true, [14] = true, [15] = true, [18] = true, [26] = true, [52] = true, [53] = true, [54] = true, [55] = true, [56] = true, [57] = true, [58] = true, [59] = true, [60] = true, [61] = true, [62] = true, [112] = true, [113] = true, [114] = true, [118] = true, [125] = true, [132] = true,
}
Config.FemaleNoVest = {
    [0] = true, [1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [9] = true, [10] = true, [11] = true, [12] = true, [13] = true, [14] = true, [15] = true, [19] = true, [59] = true, [60] = true, [61] = true, [62] = true, [63] = true, [64] = true, [65] = true, [66] = true, [67] = true, [68] = true, [69] = true, [70] = true, [71] = true, [129] = true, [130] = true, [131] = true, [135] = true, [142] = true, [149] = true, [153] = true, [157] = true, [161] = true, [165] = true,
}



Config.MaleNoMask = {
    [0] = true, [1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [9] = true, [10] = true, [11] = true, [12] = true, [13] = true, [14] = true, [15] = true, [18] = true, [26] = true, [52] = true, [53] = true, [54] = true, [55] = true, [56] = true, [57] = true, [58] = true, [59] = true, [60] = true, [61] = true, [62] = true, [112] = true, [113] = true, [114] = true, [118] = true, [125] = true, [132] = true,
}
Config.FemaleNoMask = {
    [0] = true, [1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [9] = true, [10] = true, [11] = true, [12] = true, [13] = true, [14] = true, [15] = true, [19] = true, [59] = true, [60] = true, [61] = true, [62] = true, [63] = true, [64] = true, [65] = true, [66] = true, [67] = true, [68] = true, [69] = true, [70] = true, [71] = true, [129] = true, [130] = true, [131] = true, [135] = true, [142] = true, [149] = true, [153] = true, [157] = true, [161] = true, [165] = true,
}



Config.MaleNoHats = {
    [0] = true, [1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [9] = true, [10] = true, [11] = true, [12] = true, [13] = true, [14] = true, [15] = true, [18] = true, [26] = true, [52] = true, [53] = true, [54] = true, [55] = true, [56] = true, [57] = true, [58] = true, [59] = true, [60] = true, [61] = true, [62] = true, [112] = true, [113] = true, [114] = true, [118] = true, [125] = true, [132] = true,
}
Config.FemaleNoHats = {
    [0] = true, [1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [9] = true, [10] = true, [11] = true, [12] = true, [13] = true, [14] = true, [15] = true, [19] = true, [59] = true, [60] = true, [61] = true, [62] = true, [63] = true, [64] = true, [65] = true, [66] = true, [67] = true, [68] = true, [69] = true, [70] = true, [71] = true, [129] = true, [130] = true, [131] = true, [135] = true, [142] = true, [149] = true, [153] = true, [157] = true, [161] = true, [165] = true,
}

-- CLOTHING LIST


Config.Masks = {
[0] = "No Mask Visable",
[1] = "Pig Mask Visable",
[2] = "Skeleton Mask Visable", 
[3] = "Monkey With Cigar Mask Visable",
[4] = "Hockey Mask Visable",
[5] = "Monkey Mask Visable", 
[6] = "Weird Parade Mask", 
[7] = "Vampire With Mouth Open Mask Visable", 
[8] = "Santa Mask Visable", 
[9] = "Raindeer Mask Visable", 
[10] = "Snowman Mask Visable", 
[11] = "Phantom Mask Visable", 
[12] = "Bird Mask Visable", 
[13] = "Kid With Headband Mask", 
[14] = "Blue Hockey Mask", 
[15] = "Black Hockey Mask",  
[16] = "Metal Mask", 
[17] = "Cat Mask",
[18] = "Wolf Mask", 
[19] = "Owl Mask", 
[20] = "Racoon Mask", 
[21] = "Bear Mask", 
[22] = "Ox Mask", 
[23] = "Bull Mask", 
[24] = "Hawk Mask", 
[25] = "Turkey Mask", 
[26] = "Wolf Mask", 
[27] = "Old Pilot Burlap", 
[28] = "Full Blackops Mask",
[29] = "Strap-On Skeleton Mask", 
[30] = "Yellow Hockey Mask", 
[31] = "Penguin With Hat Mask", 
[32] = "Red Sock Mask", 
[33] = "Gingerbread Mask", 
[34] = "Alcoholic Elf Mask", 
[35] = "Black Eyes Only Mask",
[36] = "Breathing Mask",
[37] = "Old Robber Mask",
[38] = "Breathing Mask",
[39] = "Broken Face Mask",
[40] = "Mumie Mask",
[41] = "Vampire Mask",
[42] = "Zombie Mask",
[43] = "Super Hero Mask",
[44] = "Anime Mask",
[45] = "Mafia Cigar Mask",
[46] = "Radiation Mask",
[47] = "Tape Mask",
[48] = "Tape Mask",
[49] = "Paper Bag Mask",
[50] = "Face Mask",
[51] = "Face-Bandana",
[52] = "Full-Face Mask",
[53] = "Ninja Mask",
[54] = "Ninja Mask",
[55] = "Ninja Mask",
[56] = "Ninja Mask",
[57] = "Balaclava Mask",
[58] = "Balaclava Mask",
[59] = "Warewolf Mask",
[60] = "Pumpkin Mask",
[61] = "Old Man Zombie Mask",
[62] = "Zombie Mask",
[63] = "Muscle Mask",
[64] = "Skeleton Mask With Head Opened",
[65] = "Warewolf Mask With Beard",
[66] = "Cockroach Mask",
[67] = "Zombie Mask",
[68] = "Devil Mask",
[69] = "Bag Mask With Rope",
[70] = "Trippy Eyes With Blue Marks",
[71] = "Goblin Mask",
[72] = "Devil Mask",
[73] = "No Mask",
[74] = "Burnt Gingerbread Mask",
[75] = "Gingerbread Mask",
[76] = "Alcoholic Santa",
[77] = "Latex X-Mas Tree",
[78] = "Meatball with white sauce mask",
[79] = "Warewolf Mask",
[80] = "Warewolf Mask With Cap",
[81] = "Warewolf Mask With Cap",
[82] = "Warewolf Mask With Headband",
[83] = "Warewolf Mask With Santa Hat",
[84] = "Yeti Mask",
[85] = "Raw Chicken Mask",
[86] = "Drunk Grandma Mask",
[87] = "Pothead Grandpa",
[88] = "X-Mas Grandma",
[89] = "Blackops Mask",
[90] = "Metal Half Mask",
[91] = "Huge Metal Mask",
[92] = "Alien Mask",
[93] = "Dinosaur Mask",
[94] = "Devil Mask",
[95] = "Clown Mask",
[96] = "Gorilla Mask",
[97] = "Horse Mask",
[98] = "Unicorn Mask",
[99] = "Design Skeleton Mask",
[100] = "Pug Mask",
[101] = "Bigness Face-Mask",
[102] = "Neon Mask",
[103] = "Zombie Mask With Military Helmet",
[104] = "Blackops Mask",
[105] = "Devil / Cult Mask",
[106] = "Full Face-Mask",
[107] = "Half-Face Mask",
[108] = "Skeleton Mask",
[109] = "Old Pilot Head Burlap",
[110] = "Blackops Mask",
[111] = "Face-Mask",
[112] = "Blackops Mask",
[113] = "Full Face Mask",
[114] = "Full Headwrap",
[115] = "Full Headwrap",
[116] = "Half Face Headwrap",
[117] = "Balaclava",
[118] = "Ninja Headwrap",
[119] = "Skeleton Face-Mask",
[120] = "No Mask",
[121] = "Ear-Peice",
[122] = "Face-Mask (Not Covering Nose or Mouth)",
[123] = "Neon Green Face-Mask",
[124] = "Neon Face-Mask",
[125] = "Blackops Mask",
[126] = "Full Face Mask",
[127] = "Gingerbread Mask",
[128] = "Camo Mask",
[129] = "Radiation Mask",
[130] = "Breathing Mask",
[131] = "Ugly Goat Mask",
[132] = "Night Vision Mask",
[133] = "Designer Hockeymask",
[134] = "Latex Robot Mask",
[135] = "Robot Mask",
[136] = "Dead Scarecrow Mask",
[137] = "Starwars Mask",
[138] = "Yeti Mask?",
[139] = "Big Brain Alien Mask",
[140] = "Cyclone Alien Mask",
[141] = "Alien Mask",
[142] = "Zombie Pilot",
[143] = "Big Taco Mask",
[144] = "Burger Mask",
[145] = "Chicken Mask (Not Covering Mouth Or Eyes)",
[146] = "Zoom Goggles",
[147] = "Big Monkey Mask With Cigar",
[148] = "Latex Eye Mask",
[149] = "Strawberry Mask",
[150] = "Lemon Mask",
[151] = "Grape Mask",
[152] = "Pinaple Mask",
[153] = "Cherry Mask",
[154] = "Mask That Says 7",
[155] = "Card Game Joker",
[156] = "King Mask",
[157] = "Queen Mask",
[158] = "Weird Dude Mask",
[159] = "Skeleton Ace Mask",
[160] = "White Baby Mask With Scar On Head",
[161] = "Yellow nad Red Mask",
[162] = "Dead Pig Mask",
[163] = "Monkey On Crack",
[164] = "Pac-Man But Broken",
[165] = "Bloddy Bunny Mask",
[166] = "Breathing Mask",
[167] = "Head-Wrap With Leaves As Hair",
[168] = "Flesh Mask",
[169] = "Half Face Mask",
[170] = "Dirty Bag With Red Lips Mask",
[171] = "Pixel Fox Mask",
[172] = "Pixel Cat Mask",
[173] = "Pixel Pig Mask",
[174] = "Blackops Mask With Red Teeth",
[175] = "Radiation Mask",
[176] = "Pixel Dog Mask",
[177] = "Radiation Mask With Radio",
[178] = "Blackops Mask With Red Teeth",
[179] = "Yellow Emoji Mask",
[180] = "Alien Mask",
[181] = "Turtle Mask",
[182] = "Mouse Mask",
[183] = "Railed Mask",
[184] = "Some Animal Mask",
[185] = "Full Face Mask",
[186] = "Face Mask",
[187] = "Half Face Mask",
[188] = "Boogar Triple Eye Mask",
[189] = "Some Weird Latex Mask",
[190] = "Animal Skeleton Head Mask",
[191] = "Some Weird Mask With Scars",
[192] = "Mask With Horns Sticking Out Of Head",
[193] = "Bear Mask",
[194] = "Full Mask",
[195] = "Full Mask"
}



Config.Vests = {
[0] = "No Vest",
[1] = "Bullet Proof Vest",
[2] = "Bullet Proof Vest",
[3] = "Bullet Proof Vest",
[4] = "Bullet Proof Vest",
[5] = "Bullet Proof Vest",
[6] = "Bullet Proof Vest",
[7] = "Bullet Proof Vest",
[8] = "Bullet Proof Vest",
[9] = "Bullet Proof Vest",
[10] = "Bullet Proof Vest",
[11] = "Bullet Proof Vest",
[12] = "Bullet Proof Vest",
[13] = "No Vest",
[14] = "No Vest",
[15] = "Heavy-Duty Bullet Proof Vest",
[16] = "Heavy-Duty Bullet Proof Vest With Extra Magasines",
[17] = "Knife Vest",
[18] = "Knife Vest",
[19] = "Knife Vest",
[20] = "Knife Vest",
[21] = "Knife Vest",
[22] = "Knife Vest",
[23] = "Knife Vest",
[24] = "Knife Vest",
[25] = "Knife Vest",
[26] = "Knife Vest",
[27] = "Knife Vest",
[28] = "Knife Vest",
[29] = "No Vest",
[30] = "No Vest",
[31] = "No Vest",
[32] = "No Vest",
[33] = "No Vest",
[34] = "No Vest",
[35] = "No Vest",
[36] = "No Vest",
[37] = "No Vest",
[38] = "No Vest",
[39] = "No Vest",
[40] = "No Vest",
[41] = "No Vest",
[42] = "No Vest",
[43] = "No Vest",
[44] = "No Vest",
[45] = "No Vest",
[46] = "No Vest",
[46] = "No Vest",
[47] = "No Vest",
[48] = "No Vest",
[49] = "No Vest",
[50] = "No Vest",
[51] = "No Vest",
[52] = "No Vest",
[53] = "FIB Badge",
[54] = "FIB Badge",
[55] = "FIB Badge",
[56] = "FIB Badge"
}
